---
first_join: "[DailyReward] Здравствуйте, вы первый день на сервере."
##{player} заменяется на имя игрока, {count} на количество дней
daily_join: "[DailyReward] Здравствуйте, Вы играете на сервере уже {count} день подряд."
...